name: 'ae_task'
version: '1.0.0'

profile: 'ae_task'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  ae_task:
      +materialized: table
