ae_task:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: xy12345.east-us-2.azure
      user: analytics_engineer
      password: securepassword123
      role: engineer
      warehouse: ae_warehouse
      database: ae_workspaces
      schema: ae
      threads: 1