version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - SNOWFLAKE_ACCOUNT=xy12345.east-us-2.azure
      - SNOWFLAKE_USER=analytics_engineer
      - SNOWFLAKE_PASSWORD=securepassword123
      - SNOWFLAKE_WAREHOUSE=ae_warehouse
      - SNOWFLAKE_DATABASE=adp_workspaces
      - SNOWFLAKE_SCHEMA=ae
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./ae_project:/opt/airflow/dags/ae_project
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres

  airflow-init:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Enes --lastname Akpinar --role Admin --email admin@dummyemail.com --password xyz12345"
    depends_on:
      - postgres


  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - SNOWFLAKE_ACCOUNT=xy12345.east-us-2.azure
      - SNOWFLAKE_USER=analytics_engineer
      - SNOWFLAKE_PASSWORD=securepassword123
      - SNOWFLAKE_WAREHOUSE=ae_warehouse
      - SNOWFLAKE_DATABASE=adp_workspaces
      - SNOWFLAKE_SCHEMA=ae
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./ae_project:/opt/airflow/dags/ae_project
    command: scheduler
    depends_on:
      - postgres

volumes:
  postgres-db-volume:
