version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5000:5000"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - SNOWFLAKE_ACCOUNT=xy12345.east-us-2.azure
      - SNOWFLAKE_USER=analytics_engineer
      - SNOWFLAKE_PASSWORD=securepassword123
      - SNOWFLAKE_WAREHOUSE=ae_warehouse
      - SNOWFLAKE_DATABASE=adp_workspaces
      - SNOWFLAKE_SCHEMA=ae
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./pipeline:/opt/airflow/pipeline
      - ./ae_task:/opt/airflow/dags/ae_task
    ports:
      - "8081:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - postgres


  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - SNOWFLAKE_ACCOUNT=xy12345.east-us-2.azure
      - SNOWFLAKE_USER=analytics_engineer
      - SNOWFLAKE_PASSWORD=securepassword123
      - SNOWFLAKE_WAREHOUSE=ae_warehouse
      - SNOWFLAKE_DATABASE=adp_workspaces
      - SNOWFLAKE_SCHEMA=ae
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
      - ./ae_task:/opt/airflow/dags/ae_task
    command: scheduler
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-db-volume:
